export const LEADING_SUIT_BOX = "LEADING_SUIT_BOX"

export const TABLE_CARDS = "TABLE_CARDS"

export const PLAYERS_LIST_ENTRY = "PLAYERS_LIST_ENTRY"

export const PLAYERS_HAND = "PLAYERS_HAND"

export const ZOOM_CARD_MODAL_FOOTER = "ZOOM_CARD_MODAL_FOOTER"
