export const PLAYER_RANKING_ENTRY = "PLAYER_RANKING_ENTRY"
export const ANTEROOM_CONTAINER = "ANTEROOM_CONTAINER"
export const LIST_GAMES_MODAL = "LIST_GAMES_MODAL"
export const EMPTY_GAMES_LIST_PLACEHOLDER = "EMPTY_GAMES_LIST_PLACEHOLDER"
